version: '3'

services:
  livraria_database:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    expose:
      - 5432
    env_file:
      - livraria_database.env

  livraria_app:
    image: alura/livraria-api
    restart: always
    ports:
      - 8089:8089
    depends_on:
      - livraria_database
    env_file:
      - livraria_app.env 